export const CARD_DECK_LABELS = Object.freeze({
  chance: "转机",
  community: "城市基金",
});

export const CARD_DECKS = Object.freeze({
  chance: Object.freeze([
    { id: "turning-point-skyline", label: "直达天际大道。", effect: { kind: "move", destination: 39, collectGo: false } },
    { id: "turning-point-departure", label: "前往“启程”。（领取 ¤200）", effect: { kind: "move", destination: 0, collectGo: true } },
    { id: "turning-point-central", label: "直达中央大道。如途经“启程”，可领取 ¤200。", effect: { kind: "move", destination: 24, collectGo: true } },
    { id: "turning-point-elm-square", label: "直达榆光广场。如途经“启程”，可领取 ¤200。", effect: { kind: "move", destination: 11, collectGo: true } },
    {
      id: "turning-point-nearest-hub",
      label: "前往最近的交通枢纽。如果尚无业主，你可以向城市银行购买；如果已有业主，则支付双倍通行费。（牌组中有两张）",
      effect: { kind: "nearest", target: "station" },
      copies: 2,
    },
    {
      id: "turning-point-nearest-utility",
      label: "前往最近的城市公共服务。如果尚无业主，你可以向城市银行购买；如果已有业主，则再掷骰子并支付点数 10 倍的使用费。",
      effect: { kind: "nearest", target: "utility" },
    },
    { id: "turning-point-dividend", label: "城市银行结算项目红利，领取 ¤50。", effect: { kind: "cash", amount: 50 } },
    { id: "turning-point-release-pass", label: "暂留所通行证，可以保留至需要时使用或参与交易。", effect: { kind: "jailFree" } },
    { id: "turning-point-back-three", label: "道路临时封闭，退后 3 格。", effect: { kind: "back", spaces: 3 } },
    { id: "turning-point-detention", label: "前往暂留所。不要经过“启程”，不能领取 ¤200。", effect: { kind: "jail" } },
    { id: "turning-point-repairs", label: "物业年度检修：每栋房屋支付 ¤25，每座地标支付 ¤100。", effect: { kind: "repairs", perHouse: 25, perHotel: 100 } },
    { id: "turning-point-traffic-fine", label: "收到交通罚单，支付 ¤15。", effect: { kind: "cash", amount: -15 } },
    { id: "turning-point-north-hub", label: "前往北港枢纽。如途经“启程”，可领取 ¤200。", effect: { kind: "move", destination: 5, collectGo: true } },
    { id: "turning-point-civic-host", label: "主办城市交流会，向每位参与者支付 ¤50。", effect: { kind: "payEach", amount: 50 } },
    { id: "turning-point-project-return", label: "旧项目完成结算，领取 ¤150。", effect: { kind: "cash", amount: 150 } },
  ]),
  community: Object.freeze([
    { id: "city-fund-departure", label: "前往“启程”。（领取 ¤200）", effect: { kind: "move", destination: 0, collectGo: true } },
    { id: "city-fund-audit-credit", label: "公共账户复核产生结余，领取 ¤200。", effect: { kind: "cash", amount: 200 } },
    { id: "city-fund-clinic", label: "支付城市诊疗费 ¤50。", effect: { kind: "cash", amount: -50 } },
    { id: "city-fund-market", label: "社区市集摊位结算，领取 ¤50。", effect: { kind: "cash", amount: 50 } },
    { id: "city-fund-release-pass", label: "暂留所通行证，可以保留至需要时使用或参与交易。", effect: { kind: "jailFree" } },
    { id: "city-fund-detention", label: "前往暂留所。不要经过“启程”，不能领取 ¤200。", effect: { kind: "jail" } },
    { id: "city-fund-festival", label: "城市节庆补助到账，领取 ¤100。", effect: { kind: "cash", amount: 100 } },
    { id: "city-fund-fee-refund", label: "城市费用复核退款，领取 ¤20。", effect: { kind: "cash", amount: 20 } },
    { id: "city-fund-neighborhood-day", label: "举办邻里开放日，向每位参与者收取 ¤10。", effect: { kind: "collectEach", amount: 10 } },
    { id: "city-fund-savings", label: "长期储蓄计划到期，领取 ¤100。", effect: { kind: "cash", amount: 100 } },
    { id: "city-fund-emergency", label: "支付紧急服务费 ¤100。", effect: { kind: "cash", amount: -100 } },
    { id: "city-fund-training", label: "支付职业培训费 ¤50。", effect: { kind: "cash", amount: -50 } },
    { id: "city-fund-design", label: "完成街区设计委托，领取 ¤25。", effect: { kind: "cash", amount: 25 } },
    { id: "city-fund-maintenance", label: "街区维护评估：每栋房屋支付 ¤40，每座地标支付 ¤115。", effect: { kind: "repairs", perHouse: 40, perHotel: 115 } },
    { id: "city-fund-volunteer", label: "获得社区志愿奖，领取 ¤10。", effect: { kind: "cash", amount: 10 } },
    { id: "city-fund-grant", label: "获得城市更新资助，领取 ¤100。", effect: { kind: "cash", amount: 100 } },
  ]),
});
